"use client";

import {type FormEvent,useEffect,useMemo,useRef,useState,useTransition} from "react";
import Image from "next/image";
import {useRouter} from "next/navigation";
import {ArrowLeft,ArrowRight,Banknote,CalendarDays,Check,CheckCircle2,Copy,Download,LoaderCircle,MapPin,MessageCircle,ReceiptText,ShieldCheck,Smartphone,Ticket,UploadCloud,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {createClient} from "@/lib/supabase/client";
import {formatBrazilCurrencyInput,formatBrazilPhone} from "@/utils/input-masks";
import type {EventDetail} from "../types/event.types";
import {buildPublicCaravanPaymentPayload,canShowPublicCashWhatsapp} from "../utils/payment-payload";
import {buildTrackingHash,PUBLIC_BACK_LABEL,PUBLIC_MANUAL_PAYMENT_SUBTITLE,shouldShowPublicSummary} from "../utils/public-registration-flow";
import * as S from "./events.styles";
import {PublicCollapsibleSummary,PublicEventHeroMeta,PublicFlowToast,type PublicFlowNotice} from "./public-event-mobile";

type Item={id:string;name:string;description:string|null;item_type:string;price:number;is_required:boolean;allow_quantity:boolean;min_quantity:number;max_quantity:number|null;available_quantity:number|null};
type Props={event:EventDetail;items:Item[];isRegistrationOpen:boolean};
type Result={groupId:string;groupNumber:string;totalAmount:number;paymentStatus:string;verificationToken:string;accessToken:string};
type FormDataState={originChurchName:string;originCity:string;originState:string;responsibleName:string;responsiblePhone:string;responsibleEmail:string;pastorName:string;pastorPhone:string;notes:string};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"full",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value));

export function PublicCaravanRegistration({event,items,isRegistrationOpen}:Props){
  const router=useRouter();
  const [pending,startTransition]=useTransition();const [step,setStep]=useState<1|2|3>(1);const [notice,setNotice]=useState<PublicFlowNotice|null>(null);
  const [total,setTotal]=useState(1);const [male,setMale]=useState(0);const [female,setFemale]=useState(1);const [formData,setFormData]=useState<FormDataState|null>(null);const [listFile,setListFile]=useState<File|null>(null);const [receiptFile,setReceiptFile]=useState<File|null>(null);const [paymentMethod,setPaymentMethod]=useState<"PIX"|"CASH"|"NOT_APPLICABLE">(event.paymentSettings.pixEnabled?"PIX":event.paymentSettings.cashEnabled?"CASH":"NOT_APPLICABLE");const [paymentAmount,setPaymentAmount]=useState(formatBrazilCurrencyInput("0"));const [pixCopied,setPixCopied]=useState(false);const [result,setResult]=useState<Result|null>(null);
  const sessionKey=useRef(`caravan_${crypto.randomUUID()}`);const idempotencyKey=useRef(`caravan_${crypto.randomUUID()}`);
  const caravanFormId=`event-public-caravan-${event.id}`;const trackingPath=`/inscricoes/${event.publicCode}/${event.slug}/acompanhar`;
  const mainItemId=event.paymentSettings.caravanRegistrationItemId||items.find((item)=>item.item_type==="REGISTRATION")?.id||"";
  const [selected,setSelected]=useState(()=>new Set(items.filter((item)=>item.is_required||item.id===mainItemId).map((item)=>item.id)));const [quantities,setQuantities]=useState<Record<string,number>>({});
  const selectedItems=useMemo(()=>items.filter((item)=>selected.has(item.id)).map((item)=>({...item,quantity:item.id===mainItemId?total:Math.max(1,quantities[item.id]??item.min_quantity??1)})),[items,mainItemId,quantities,selected,total]);
  const totalAmount=selectedItems.reduce((sum,item)=>sum+item.price*item.quantity,0);
  const paymentOptions=[...(event.paymentSettings.pixEnabled?[{value:"PIX" as const,label:"Pix estático",icon:Smartphone}]:[]),...(event.paymentSettings.cashEnabled?[{value:"CASH" as const,label:"Dinheiro",icon:Banknote}]:[])];

  useEffect(()=>{
    const warn=(before:BeforeUnloadEvent)=>{if(!result&&(formData||step>1)){before.preventDefault();before.returnValue="";}};
    window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);
  },[formData,result,step]);

  async function upload(kind:"list"|"receipt",file:File){
    const response=await fetch(`/api/public/events/${event.publicCode}/${event.slug}/groups/uploads`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:event.id,sessionKey:sessionKey.current,kind,fileName:file.name,mimeType:file.type,fileSize:file.size})});const body=await response.json() as {message?:string;data?:{path:string;token:string}};if(!response.ok||!body.data)throw new Error(body.message??"Não foi possível preparar o arquivo.");
    const sent=await createClient().storage.from("event-documents").uploadToSignedUrl(body.data.path,body.data.token,file,{contentType:file.type});if(sent.error)throw new Error("Não foi possível enviar o arquivo.");return body.data.path;
  }

  function submitData(submit:FormEvent<HTMLFormElement>){
    submit.preventDefault();if(total!==male+female){setNotice({message:"A quantidade total deve ser igual à soma de masculino e feminino.",danger:true});return;}
    const raw=new FormData(submit.currentTarget);const nextData={originChurchName:String(raw.get("originChurchName")??""),originCity:String(raw.get("originCity")??""),originState:String(raw.get("originState")??"").toUpperCase(),responsibleName:String(raw.get("responsibleName")??""),responsiblePhone:String(raw.get("responsiblePhone")??""),responsibleEmail:String(raw.get("responsibleEmail")??""),pastorName:String(raw.get("pastorName")??""),pastorPhone:String(raw.get("pastorPhone")??""),notes:String(raw.get("notes")??"")};
    startTransition(async()=>{try{setNotice(null);const payload={eventId:event.id,sessionKey:sessionKey.current,...nextData,totalRegistrations:total,maleCount:male,femaleCount:female,items:selectedItems.map((item)=>({itemId:item.id,quantity:item.quantity}))};const response=await fetch(`/api/public/events/${event.publicCode}/${event.slug}/groups/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message??"Não foi possível validar a caravana.");setFormData(nextData);setPaymentAmount(formatBrazilCurrencyInput(String(Math.round(totalAmount*100))));setStep(2);window.scrollTo({top:0,behavior:"smooth"});}catch(error){setNotice({message:error instanceof Error?error.message:"Não foi possível validar a caravana.",danger:true});}});
  }

  function finish(){if(!formData)return;startTransition(async()=>{try{setNotice(null);const selectedMethod=totalAmount<=0?"NOT_APPLICABLE":paymentMethod;const receiptToUpload=selectedMethod==="PIX"?receiptFile:null;const informedAmount=receiptToUpload?Number(paymentAmount.replace(/[^0-9]/g,""))/100:0;if(receiptToUpload&&(!Number.isFinite(informedAmount)||informedAmount<=0||informedAmount>totalAmount))throw new Error("Informe um valor pago maior que zero e não superior ao total da caravana.");const [listPath,receiptPath]=await Promise.all([listFile?upload("list",listFile):Promise.resolve(""),receiptToUpload?upload("receipt",receiptToUpload):Promise.resolve("")]);const payment=buildPublicCaravanPaymentPayload({paymentMethod:selectedMethod,amountValue:paymentAmount,receipt:receiptToUpload?{path:receiptPath,fileName:receiptToUpload.name,mimeType:receiptToUpload.type,fileSize:receiptToUpload.size}:null});const payload={eventId:event.id,sessionKey:sessionKey.current,...formData,totalRegistrations:total,maleCount:male,femaleCount:female,items:selectedItems.map((item)=>({itemId:item.id,quantity:item.quantity})),...payment,listPath,listFileName:listFile?.name??"",listMimeType:listFile?.type??"",listFileSize:listFile?.size??0,website:""};const response=await fetch(`/api/public/events/${event.publicCode}/${event.slug}/groups`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":idempotencyKey.current},body:JSON.stringify(payload)});const body=await response.json() as {message?:string;data?:Result};if(!response.ok||!body.data)throw new Error(body.message??"Não foi possível concluir a inscrição.");setResult(body.data);sessionStorage.setItem(`eklesia:event-tracking:${event.id}`,body.data.accessToken);router.push(`${trackingPath}${buildTrackingHash("CARAVAN",body.data.accessToken)}`);}catch(error){setNotice({message:error instanceof Error?error.message:"Não foi possível concluir a inscrição.",danger:true});}});}

  async function copyPix(){await navigator.clipboard.writeText(event.paymentSettings.pixKey);setPixCopied(true);setNotice({message:"Chave Pix copiada."});window.setTimeout(()=>setPixCopied(false),2600);}
  const whatsappNumber=(event.paymentSettings.whatsappNumber??"").replace(/\D/g,"");
  const cashWhatsapp=result&&canShowPublicCashWhatsapp({completed:true,paymentMethod,hasWhatsappNumber:Boolean(whatsappNumber)})?`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(`Olá! Gostaria de combinar o pagamento em dinheiro da caravana ${result.groupNumber} — ${event.name}. Responsável: ${formData?.responsibleName}. Origem: ${formData?.originChurchName}. Total: ${money(result.totalAmount)}.`)}`:"";
  const summaryState=shouldShowPublicSummary({step,completed:Boolean(result)});
  function goBack(){if(step===3)setStep(2);else if(step===2)setStep(1);else router.push(`/inscricoes/${event.publicCode}/${event.slug}?nova=1`);window.scrollTo({top:0,behavior:"smooth"});}

  return <S.PublicShell><S.PublicCard><S.PublicHero $image={event.bannerUrl}><div><span>{isRegistrationOpen?"INSCRIÇÕES DE CARAVANA ABERTAS":"INSCRIÇÕES ENCERRADAS"}</span><h1>{event.name}</h1><PublicEventHeroMeta startsAt={event.startsAt} location={[event.location,event.city,event.state].filter(Boolean).join(" · ")}/></div></S.PublicHero>
    <S.CheckoutStepper aria-label={`Etapa ${step} de 3`}>{[{id:1,label:"Dados da caravana",icon:Users},{id:2,label:"Pagamento",icon:Smartphone},{id:3,label:"Comprovante",icon:ReceiptText}].map((item)=>{const Icon=item.icon;return <div key={item.id} aria-current={step===item.id?"step":undefined} data-done={item.id<step}><span>{item.id<step?<Check/>:<Icon/>}</span><div><small>Etapa {item.id}</small><strong>{item.label}</strong></div></div>;})}</S.CheckoutStepper>
    <S.PublicContent><section>
      {!result?<S.PublicBackRow aria-label="Navegação de retorno"><S.PublicBackButton type="button" onClick={goBack}><ArrowLeft/>{PUBLIC_BACK_LABEL}</S.PublicBackButton></S.PublicBackRow>:null}
      {step===1?<S.CheckoutPanel><S.PublicStepHeading><small>ETAPA 1 DE 3</small><h2>Dados e quantidades</h2><p>Informe a origem, o responsável e as quantidades agregadas da caravana.</p></S.PublicStepHeading>{isRegistrationOpen?<form id={caravanFormId} onSubmit={submitData}><S.FieldGrid><S.Field><span>Igreja/origem *</span><input name="originChurchName" required minLength={2} defaultValue={formData?.originChurchName??""}/></S.Field><S.Field><span>Cidade *</span><input name="originCity" required minLength={2} defaultValue={formData?.originCity??""}/></S.Field><S.Field><span>UF *</span><input name="originState" required minLength={2} maxLength={2} defaultValue={formData?.originState??""}/></S.Field><S.Field><span>Responsável da caravana *</span><input name="responsibleName" required minLength={3} defaultValue={formData?.responsibleName??""}/></S.Field><S.Field><span>Telefone *</span><input name="responsiblePhone" required minLength={8} inputMode="tel" defaultValue={formData?.responsiblePhone??""} onChange={(change)=>{change.currentTarget.value=formatBrazilPhone(change.currentTarget.value);}}/></S.Field><S.Field><span>E-mail</span><input name="responsibleEmail" type="email" defaultValue={formData?.responsibleEmail??""}/></S.Field><S.Field><span>Pastor(a) *</span><input name="pastorName" required minLength={2} defaultValue={formData?.pastorName??""}/></S.Field><S.Field><span>Telefone do pastor(a)</span><input name="pastorPhone" inputMode="tel" defaultValue={formData?.pastorPhone??""} onChange={(change)=>{change.currentTarget.value=formatBrazilPhone(change.currentTarget.value);}}/></S.Field><S.Field><span>Quantidade total *</span><input type="number" min={1} required value={total} onChange={(change)=>setTotal(Number(change.target.value))}/></S.Field><S.Field><span>Masculino *</span><input type="number" min={0} required value={male} onChange={(change)=>setMale(Number(change.target.value))}/></S.Field><S.Field><span>Feminino *</span><input type="number" min={0} required value={female} onChange={(change)=>setFemale(Number(change.target.value))}/></S.Field><S.Field><span>Conferência</span><input readOnly value={total===male+female?"Totais conferem":"Revise as quantidades"} aria-invalid={total!==male+female}/></S.Field>
        <S.Wide><fieldset><S.FieldLegend>Itens da caravana</S.FieldLegend><S.PublicItemCards>{items.map((item)=><S.PublicItemCard key={item.id} $selected={selected.has(item.id)}><input type="checkbox" checked={selected.has(item.id)} disabled={item.is_required||item.id===mainItemId} onChange={()=>setSelected((current)=>{const next=new Set(current);if(next.has(item.id))next.delete(item.id);else next.add(item.id);return next;})}/><span><Ticket/></span><div><strong>{item.name}</strong><small>{money(item.price)}{item.id===mainItemId?` · ${total} participantes`:""}</small></div>{selected.has(item.id)&&item.id!==mainItemId?<input aria-label={`Quantidade de ${item.name}`} type="number" min={1} value={quantities[item.id]??1} onChange={(change)=>setQuantities((current)=>({...current,[item.id]:Number(change.target.value)}))}/>:null}</S.PublicItemCard>)}</S.PublicItemCards></fieldset></S.Wide>
        {event.paymentSettings.allowParticipantList?<S.Wide><S.DropField><input type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx,.docx" onChange={(change)=>setListFile(change.target.files?.[0]??null)}/><UploadCloud/><strong>{listFile?.name??"Lista de participantes (opcional)"}</strong><small>PDF, imagem, XLSX ou DOCX de até 10 MB</small></S.DropField></S.Wide>:null}<S.Wide><S.Field><span>Observações</span><textarea name="notes" maxLength={1000} defaultValue={formData?.notes??""}/></S.Field></S.Wide></S.FieldGrid><S.DesktopPublicActions><Button type="submit" loading={pending}>Validar e continuar<ArrowRight size={16}/></Button></S.DesktopPublicActions></form>:<S.Notice $danger>As inscrições deste evento estão encerradas.</S.Notice>}</S.CheckoutPanel>:null}
      {step===2?<S.CheckoutPanel><S.PublicStepHeading><small>ETAPA 2 DE 3</small><h2>Pagamento coletivo</h2><p>{paymentMethod==="CASH"?"Na próxima etapa, conclua a inscrição para receber o contato do WhatsApp.":"Confira os dados Pix do evento antes de prosseguir."}</p></S.PublicStepHeading>{totalAmount<=0?<S.Notice>Esta caravana não possui valor a pagar.</S.Notice>:<><S.PaymentChoices>{paymentOptions.map((option)=>{const Icon=option.icon;return <label key={option.value} data-selected={paymentMethod===option.value}><input type="radio" checked={paymentMethod===option.value} onChange={()=>setPaymentMethod(option.value)}/><span><Icon/></span><div><strong>{option.label}</strong><small>{option.value==="PIX"?"Pagamento com os dados estáticos do evento":"Pagamento presencial"}</small></div></label>;})}</S.PaymentChoices>{paymentMethod==="PIX"?<S.CaravanPixPanel><S.CaravanPixInfo><S.CaravanPixHeader><span><Smartphone/></span><div><small>DADOS DE PAGAMENTO</small><strong>PIX do evento</strong></div></S.CaravanPixHeader><S.CaravanPixBody><p>Titular</p><b>{event.paymentSettings.pixHolderName||"Favorecido não informado"}</b><p>Chave PIX</p><S.PixKeyInput><input readOnly value={event.paymentSettings.pixKey} aria-label="Chave PIX do evento"/><button type="button" onClick={copyPix} aria-label={pixCopied?"Chave copiada":"Copiar chave PIX"} title={pixCopied?"Chave copiada":"Copiar chave PIX"}>{pixCopied?<Check/>:<Copy/>}</button></S.PixKeyInput></S.CaravanPixBody></S.CaravanPixInfo><S.CaravanPixQr>{event.paymentSettings.pixQrUrl?<Image src={event.paymentSettings.pixQrUrl} alt="QR Code Pix do evento" width={160} height={160} unoptimized/>:<><Smartphone/><small>QR Code não cadastrado</small></>}</S.CaravanPixQr></S.CaravanPixPanel>:<S.ManualPayment><span><Banknote/></span><h3>Pagamento em dinheiro</h3><p>Conclua primeiro a inscrição. Depois, use o WhatsApp do evento para combinar o pagamento presencial com a organização.</p></S.ManualPayment>}{event.paymentSettings.paymentInstructions?<S.Notice>{event.paymentSettings.paymentInstructions}</S.Notice>:null}</>}<S.PublicPrimaryActions><Button type="button" onClick={()=>setStep(3)}>Continuar<ArrowRight size={16}/></Button></S.PublicPrimaryActions></S.CheckoutPanel>:null}
      {step===3?<S.CheckoutPanel>
        {result?<S.PublicStepHeading><small>ETAPA 3 DE 3</small><h2>Inscrição concluída</h2><p>Guarde o número da caravana para qualquer atendimento.</p></S.PublicStepHeading>:paymentMethod==="PIX"?<S.PublicStepHeading><small>ETAPA 3 DE 3</small><h2>Comprovante do Pix</h2><p>Anexe o comprovante ou finalize com pagamento pendente.</p></S.PublicStepHeading>:null}
        {result?<S.ConfirmationPanel><S.ConfirmationHeader><span><CheckCircle2/></span><div><small>CARAVANA RECEBIDA</small><h2>{result.groupNumber}</h2><p>Pagamento: {result.paymentStatus==="PAID"?"pago":result.paymentStatus==="PARTIAL"?"parcial":"pendente"}.</p></div></S.ConfirmationHeader><S.PublicActions><S.PublicDownloadLink href={`/api/public/events/${event.publicCode}/${event.slug}/groups/${result.accessToken}/receipt`} target="_blank" rel="noreferrer"><Download/>Baixar comprovante</S.PublicDownloadLink>{cashWhatsapp?<S.PublicWhatsappLink href={cashWhatsapp} target="_blank" rel="noreferrer"><MessageCircle/>Abrir WhatsApp</S.PublicWhatsappLink>:null}</S.PublicActions></S.ConfirmationPanel>:paymentMethod==="PIX"?<><S.FieldGrid><S.Field><span>Valor informado como pago</span><input value={paymentAmount} onChange={(change)=>setPaymentAmount(formatBrazilCurrencyInput(change.target.value))} inputMode="numeric" disabled={!receiptFile}/></S.Field><S.Wide><S.DropField><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={(change)=>setReceiptFile(change.target.files?.[0]??null)}/><ReceiptText/><strong>{receiptFile?.name??"Anexar comprovante (opcional)"}</strong><small>Pagamentos parciais são permitidos</small></S.DropField></S.Wide></S.FieldGrid><S.PublicPrimaryActions><Button type="button" onClick={finish} loading={pending}>{receiptFile?<><UploadCloud size={16}/>Enviar e concluir</>:<><CheckCircle2 size={16}/>Concluir com pagamento pendente</>}</Button></S.PublicPrimaryActions></>:<><S.ManualPayment><span><Banknote/></span><h3>Pagamento presencial</h3><p>{PUBLIC_MANUAL_PAYMENT_SUBTITLE}</p><S.ManualPaymentHint><CheckCircle2/><span>Nenhum comprovante é necessário para continuar.</span></S.ManualPaymentHint></S.ManualPayment><S.PublicPrimaryActions><Button type="button" onClick={finish} loading={pending}><CheckCircle2 size={16}/>Concluir inscrição</Button></S.PublicPrimaryActions></>}
      </S.CheckoutPanel>:null}
    </section><S.PublicAside><S.EventInfoCard><h3>Informações do evento</h3><p><CalendarDays/><span>{date(event.startsAt)}</span></p><p><MapPin/><span>{[event.location,event.city,event.state].filter(Boolean).join(" · ")||"Local a definir"}</span></p><p><ShieldCheck/><span>Arquivos privados e acesso protegido.</span></p></S.EventInfoCard>{summaryState.visible?<><PublicCollapsibleSummary key={`summary-${step}`} title="Resumo da caravana" total={money(totalAmount)} collapsible={summaryState.collapsible} defaultOpen={summaryState.defaultOpen}><S.CartSummary><h3>Resumo da caravana</h3><ul>{selectedItems.map((item)=><li key={item.id}><span>{item.quantity}× {item.name}</span><strong>{money(item.price*item.quantity)}</strong></li>)}</ul><footer><span>Total</span><strong>{money(totalAmount)}</strong></footer><S.SummaryMeta><span>Participantes</span><strong>{total}</strong><span>Masculino / feminino</span><strong>{male} / {female}</strong></S.SummaryMeta></S.CartSummary></PublicCollapsibleSummary>{step===1&&isRegistrationOpen?<S.CaravanSummaryAction><Button type="submit" form={caravanFormId} loading={pending} fullWidth>Validar e continuar<ArrowRight size={16}/></Button></S.CaravanSummaryAction>:null}</>:null}</S.PublicAside></S.PublicContent>
  </S.PublicCard><PublicFlowToast notice={notice} onClose={()=>setNotice(null)}/>{pending?<S.ScreenReaderStatus role="status"><LoaderCircle/>Processando</S.ScreenReaderStatus>:null}</S.PublicShell>;
}
