import "server-only";

import {PDFDocument,StandardFonts,rgb} from "pdf-lib";
import {createQrMatrix} from "../utils/qr-code";
import type {CaravanReceiptData} from "./event-caravan-receipt.service";

const blue=rgb(.25,.36,.65),ink=rgb(.06,.1,.18),muted=rgb(.4,.45,.54),line=rgb(.89,.91,.94),success=rgb(.08,.5,.3),warning=rgb(.82,.45,.06);
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value));
const status=(value:string)=>({NOT_REQUIRED:"Não necessário",PENDING:"Pendente",PARTIAL:"Parcialmente pago",PAID:"Pago",REFUNDED:"Estornado"}[value]??value);

export async function createCaravanReceiptPdf(data:CaravanReceiptData){
  const document=await PDFDocument.create();const regular=await document.embedFont(StandardFonts.Helvetica);const bold=await document.embedFont(StandardFonts.HelveticaBold);const page=document.addPage([595.28,841.89]);const {height}=page.getSize();
  page.drawRectangle({x:0,y:height-134,width:595.28,height:134,color:blue});page.drawText("EKLESIA · EVENTOS",{x:44,y:height-42,size:10,font:bold,color:rgb(1,1,1)});page.drawText(data.eventName.slice(0,58),{x:44,y:height-72,size:21,font:bold,color:rgb(1,1,1)});page.drawText("Comprovante coletivo de inscrição",{x:44,y:height-94,size:10,font:regular,color:rgb(.9,.93,1)});page.drawText(`${data.hostChurchName} · ${[data.hostChurchCity,data.hostChurchState].filter(Boolean).join("/")}`.slice(0,82),{x:44,y:height-113,size:9,font:regular,color:rgb(.9,.93,1)});const pastors=[data.seniorPastorName,data.seniorPastorSpouseName].filter(Boolean).join(" e ");if(pastors)page.drawText(`Pastores Presidentes: ${pastors}`.slice(0,86),{x:44,y:height-128,size:8,font:regular,color:rgb(.87,.91,1)});
  let y=height-165;const row=(label:string,value:string)=>{page.drawText(label,{x:44,y,size:8.5,font:regular,color:muted});page.drawText(value.slice(0,72),{x:205,y,size:9.5,font:bold,color:ink});y-=23;};
  row("Número",data.groupNumber);row("Igreja da caravana",data.originChurchName);row("Cidade / UF",`${data.originCity} / ${data.originState}`);row("Pastor(a) da caravana",data.pastorName);row("Responsável",`${data.responsibleName} · ${data.responsiblePhone}`);row("Participantes",`${data.totalRegistrations} total · ${data.maleCount} masculino · ${data.femaleCount} feminino`);row("Cadastro",date(data.createdAt));
  page.drawLine({start:{x:44,y:y+8},end:{x:551,y:y+8},thickness:1,color:line});page.drawText("Itens da caravana",{x:44,y:y-13,size:12,font:bold,color:ink});y-=38;
  for(const item of data.items.slice(0,9)){page.drawText(`${item.quantity}x  ${item.name}`.slice(0,54),{x:44,y,size:9,font:regular,color:ink});const subtotal=money(item.totalPrice);page.drawText(subtotal,{x:551-bold.widthOfTextAtSize(subtotal,9),y,size:9,font:bold,color:ink});y-=21;}
  page.drawLine({start:{x:44,y:y+6},end:{x:551,y:y+6},thickness:1,color:line});y-=18;const finance=[['Valor total',money(data.totalAmount)],['Valor pago',money(data.paidAmount)],['Saldo',money(data.remainingAmount)],['Situação',status(data.paymentStatus)]] as const;for(const [label,value] of finance){page.drawText(label,{x:44,y,size:9,font:regular,color:muted});page.drawText(value,{x:230,y,size:10,font:bold,color:label==='Situação'?(data.paymentStatus==='PAID'?success:warning):ink});y-=22;}
  const verificationY=72;page.drawRectangle({x:44,y:verificationY,width:507,height:180,color:rgb(.965,.975,1),borderColor:rgb(.82,.86,.95),borderWidth:1});page.drawText("VALIDAÇÃO DO COMPROVANTE",{x:65,y:verificationY+146,size:9,font:bold,color:blue});page.drawText(data.groupNumber,{x:65,y:verificationY+116,size:18,font:bold,color:ink});page.drawText(`Código: ${data.verificationToken}`,{x:65,y:verificationY+90,size:8,font:regular,color:muted});page.drawText("Consulte /verificar/caravana com este código.",{x:65,y:verificationY+67,size:8,font:regular,color:muted});page.drawText(data.paymentStatus==='PAID'?"Pagamento integral confirmado.":`Este documento não declara quitação. Saldo: ${money(data.remainingAmount)}`,{x:65,y:verificationY+42,size:8.5,font:bold,color:data.paymentStatus==='PAID'?success:warning});
  const relative=`/verificar/caravana/${data.verificationToken}`;const matrix=createQrMatrix(relative);const qrSize=132,quiet=4,moduleSize=qrSize/(matrix.length+quiet*2),qrX=399,qrY=verificationY+24;page.drawRectangle({x:qrX,y:qrY,width:qrSize,height:qrSize,color:rgb(1,1,1)});matrix.forEach((modules,rowIndex)=>modules.forEach((dark,columnIndex)=>{if(dark)page.drawRectangle({x:qrX+(columnIndex+quiet)*moduleSize,y:qrY+qrSize-(rowIndex+quiet+1)*moduleSize,width:moduleSize+.05,height:moduleSize+.05,color:ink});}));
  page.drawText(`Emitido em ${date(new Date().toISOString())}`,{x:44,y:40,size:8,font:regular,color:muted});page.drawText("EKLESIA",{x:551-bold.widthOfTextAtSize("EKLESIA",8),y:40,size:8,font:bold,color:blue});return Buffer.from(await document.save());
}
