"use client";
import {useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {Plus,ArrowUpRight,ArrowLeftRight,Pencil,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import type {FinanceCatalogs} from "../types/finance-catalog.types";
import type {FinanceCapabilities} from "../types/finance.types";
import type {FinanceTransactionDetail,FinanceTransactionPage} from "../types/finance-query.types";
import type {FinanceFilters} from "../validations/finance-query.schemas";
import {formatMoney} from "../utils/finance-money";
import {FinanceTransactionsTable} from "./finance-transactions-table";
import {FinanceTransactionDrawer} from "./finance-transaction-drawer";
import {FinanceCancellationDialog} from "./finance-correction-dialog";
import {FinanceTransferDialog,type TransferRow} from "./finance-transfer-dialog";
export function FinanceTransactionsWorkspace({unit,month,date,catalogs,capabilities,result,filters,transfers,newEntry}:{unit:string;month:string;date:string;catalogs:FinanceCatalogs;capabilities:FinanceCapabilities;result:FinanceTransactionPage;filters:FinanceFilters;transfers:{items:TransferRow[];page:number;pageCount:number};newEntry:boolean}){
 const [entry,setEntry]=useState<{direction:"INCOME"|"EXPENSE";transaction?:FinanceTransactionDetail}|null>(newEntry&&capabilities.create?{direction:"INCOME"}:null),[cancel,setCancel]=useState<{id:string;revision:number;kind:"CANCEL_TRANSACTION"|"CANCEL_ATTENDANCE"|"CANCEL_TRANSFER"}|null>(null),[transfer,setTransfer]=useState<{existing?:TransferRow}|null>(null),router=useRouter(),search=useSearchParams();
 return <div className="stack"><FinanceTransactionsTable unit={unit} month={month} catalogs={catalogs} result={result} filters={filters} actions={<div className="row">{capabilities.transfer&&<Button variant="outline" onClick={()=>setTransfer({})}><ArrowLeftRight size={16}/>Transferir</Button>}{capabilities.create&&<><Button variant="outline" onClick={()=>setEntry({direction:"EXPENSE"})}><ArrowUpRight size={16}/>Nova saída</Button><Button onClick={()=>setEntry({direction:"INCOME"})}><Plus size={16}/>Nova entrada</Button></>}</div>} detailActions={(t,close)=>t.status!=="CANCELLED"?<>{capabilities.update&&<Button variant="outline" onClick={()=>{close();setEntry({direction:t.direction,transaction:t});}}><Pencil size={15}/>Corrigir</Button>}{capabilities.cancel&&<><Button variant="danger" onClick={()=>{close();setCancel({id:t.id,revision:t.revision,kind:"CANCEL_TRANSACTION"});}}>Cancelar lançamento</Button>{t.attendanceId&&<Button variant="outline" onClick={()=>{close();setCancel({id:t.attendanceId!,revision:t.attendanceRevision!,kind:"CANCEL_ATTENDANCE"});}}>Cancelar atendimento</Button>}</>}</>:undefined}/>
 {transfers.items.length>0&&<section className="card stack"><h2>Transferências entre caixas</h2><div className="table-scroll"><table><thead><tr><th>Data</th><th>Origem → destino</th><th>Valor</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{transfers.items.map(t=><tr key={t.id}><td>{t.date.split("-").reverse().join("/")}</td><td>{catalogs.cashboxes.find(b=>b.id===t.sourceCashboxId)?.name} → {catalogs.cashboxes.find(b=>b.id===t.targetCashboxId)?.name}<div className="muted">{t.description}</div></td><td className="money">{formatMoney(t.amountCents)}</td><td>{t.status==="CANCELLED"?"Cancelada":"Confirmada"}</td><td>{capabilities.transfer&&t.status!=="CANCELLED"&&<div className="row"><Button variant="outline" size="sm" aria-label="Corrigir transferência" onClick={()=>setTransfer({existing:t})}><Pencil size={14}/></Button><Button variant="outline" size="sm" aria-label="Cancelar transferência" onClick={()=>setCancel({id:t.id,revision:t.revision,kind:"CANCEL_TRANSFER"})}><X size={14}/></Button></div>}</td></tr>)}</tbody></table></div>{transfers.pageCount>1&&<div className="row"><span className="muted">Página {transfers.page} de {transfers.pageCount}</span>{[-1,1].map(delta=><Button key={delta} variant="outline" disabled={transfers.page+delta<1||transfers.page+delta>transfers.pageCount} onClick={()=>{const q=new URLSearchParams(search);q.set('transferPage',String(transfers.page+delta));router.push(`/financeiro/lancamentos?${q}`,{scroll:false});}}>{delta<0?"Anterior":"Próxima"}</Button>)}</div>}</section>}
 {entry&&<FinanceTransactionDrawer unit={unit} month={month} date={date} catalogs={catalogs} capabilities={capabilities} direction={entry.direction} initialTransaction={entry.transaction} onClose={()=>setEntry(null)}/>}{cancel&&<FinanceCancellationDialog unit={unit} {...cancel} onClose={()=>setCancel(null)}/>}{transfer&&<FinanceTransferDialog unit={unit} date={date} boxes={catalogs.cashboxes} existing={transfer.existing} onClose={()=>setTransfer(null)}/>}</div>;
}
