"use client";
import {useRef,useState} from "react";
import {Search,UserCheck,QrCode} from "lucide-react";
import {Button} from "@/components/ui/button";
import type {ContributorRef} from "../types/finance-command.types";
import type {ContributorOption,ContributorSearch} from "../types/finance-contributor.types";
import {FinanceCredentialReader} from "./finance-credential-reader";
import {searchFinanceContributorsAction} from "../actions/finance-contributor.actions";
export function FinanceContributorPicker({unit,value,label,canLookup,onChange,allowCollective=true}:{unit:string;value:ContributorRef|null;label:string;canLookup:boolean;onChange:(value:ContributorRef|null,label:string,classification?:string|null)=>void;allowCollective?:boolean}){
 const [kind,setKind]=useState(value?.kind??(canLookup?"MEMBER":"UNREGISTERED")),[searchKind,setSearchKind]=useState<ContributorSearch["kind"]>("NAME"),[query,setQuery]=useState(""),[camera,setCamera]=useState(false),[results,setResults]=useState<ContributorOption[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),sequence=useRef(0);
 async function search(raw?:string){const request=++sequence.current;setBusy(true);setError("");try{const result=await searchFinanceContributorsAction(unit,{kind:raw?"CREDENTIAL":searchKind,value:raw??query});if(request!==sequence.current)return;if(result.ok){setResults(result.data);if(!result.data.length)setError("Nenhuma pessoa encontrada. Confira a busca ou identifique como não cadastrada.");}else setError(result.message);}catch{setError("Não foi possível concluir a busca.");}finally{if(request===sequence.current)setBusy(false);}}
 return <div className="stack"><label>Identificação<select value={kind} onChange={e=>{++sequence.current;setBusy(false);const next=e.target.value as typeof kind;setKind(next);setResults([]);setQuery("");setError("");onChange(next==="COLLECTIVE"?{kind:"COLLECTIVE"}:next==="UNREGISTERED"?{kind:"UNREGISTERED",name:""}:null,"");}}>{canLookup&&<option value="MEMBER">Pessoa cadastrada</option>}<option value="UNREGISTERED">Pessoa não cadastrada</option>{allowCollective&&<option value="COLLECTIVE">Contribuição coletiva</option>}</select></label>
 {kind==="UNREGISTERED"&&<label>Nome da pessoa<input value={value?.kind==="UNREGISTERED"?value.name:""} onChange={e=>onChange({kind:"UNREGISTERED",name:e.target.value},e.target.value)} required minLength={2} maxLength={160}/></label>}
 {kind==="MEMBER"&&value?.kind==="MEMBER"?<div className="notice row"><UserCheck size={20}/><strong>{label}</strong><Button variant="outline" size="sm" onClick={()=>{onChange(null,"");setResults([]);setQuery("");}}>Trocar pessoa</Button></div>:kind==="MEMBER"&&<><div className="grid"><label>Buscar por<select value={searchKind} onChange={e=>{++sequence.current;setBusy(false);setSearchKind(e.target.value as ContributorSearch["kind"]);setQuery("");setResults([]);}}><option value="NAME">Nome</option><option value="CPF">CPF</option><option value="MEMBER_CODE">Matrícula</option><option value="CREDENTIAL">QR da credencial</option></select></label><label>{searchKind==="CPF"?"CPF":searchKind==="MEMBER_CODE"?"Matrícula":searchKind==="CREDENTIAL"?"Conteúdo do QR da credencial":"Nome para busca"}<input value={query} onChange={e=>{++sequence.current;setBusy(false);setResults([]);setQuery(e.target.value);}} autoComplete="off" maxLength={searchKind==="CREDENTIAL"?2048:160} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void search();}}}/></label></div><Button variant="outline" onClick={()=>setCamera(true)}><QrCode size={16}/>Ler credencial com a câmera</Button><Button variant="outline" loading={busy} onClick={()=>void search()}><Search size={15}/>Buscar pessoa</Button><div aria-live="polite">{error&&<p role="alert">{error}</p>}{results.map(r=><Button key={r.id} variant="outline" fullWidth style={{justifyContent:"space-between",marginTop:8}} onClick={()=>{++sequence.current;setQuery("");setResults([]);onChange({kind:"MEMBER",memberId:r.id},r.name,r.suggestedClassificationId);}}><span>{r.name}<small style={{display:"block",fontWeight:400}}>{r.congregationName} · {r.memberCode??"Sem matrícula"}</small></span><UserCheck size={17}/></Button>)}</div></>}
 {camera&&<FinanceCredentialReader onClose={()=>setCamera(false)} onRead={raw=>{setCamera(false);void search(raw);}}/>}</div>;
}
