"use client";
import {useEffect,useRef,useState,useCallback} from "react";
import {Printer} from "lucide-react";
import {Button} from "@/components/ui/button";
import type {ReceiptDTO} from "../types/finance-command.types";
import {formatMoney} from "../utils/finance-money";
import {recordFinancePrintAction} from "../actions/finance-receipt.actions";
export function FinanceReceipt({receipt,unit,autoPrint=false}:{receipt:ReceiptDTO;unit:string;autoPrint?:boolean}){
 const [width,setWidth]=useState(80),[error,setError]=useState(""),[busy,setBusy]=useState(false),started=useRef(false);
 const requestPrint=useCallback(async()=>{setBusy(true);setError("");try{const result=await recordFinancePrintAction(unit,receipt.id);if(!result.ok){setError(result.message);return;}window.print();}catch{setError("Não foi possível abrir a impressão. O lançamento continua confirmado; tente novamente.");}finally{setBusy(false);}},[unit,receipt.id]);
 useEffect(()=>{if(autoPrint&&!started.current){started.current=true;void requestPrint();}},[autoPrint,requestPrint]);
 return <div className="stack"><style>{`@media print{@page{size:${width}mm auto;margin:3mm}html,body{background:white!important}.financial-receipt{width:${width-6}mm!important;max-width:${width-6}mm!important;border:0!important;padding:0!important;margin:0!important;font-size:10px!important}.financial-receipt h1{font-size:17px!important}.financial-receipt .receipt-number{overflow-wrap:anywhere}}`}</style><div className="no-print row"><label>Largura do papel<select value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={80}>80 mm</option><option value={58}>58 mm</option></select></label><Button loading={busy} onClick={()=>void requestPrint()}><Printer size={16}/>Imprimir comprovante</Button><span className="muted">O navegador abrirá a escolha da impressora.</span></div>{error&&<div role="alert" className="no-print">{error}</div>}
 <article className="financial-receipt card stack" style={{width:`${width}mm`,maxWidth:"100%",margin:"0 auto",fontSize:12,gap:12,padding:18,color:"black"}}><header style={{textAlign:"center"}}><h1 style={{fontSize:23}}>eclesias</h1><strong>{receipt.congregationName}</strong><p>{receipt.direction==="EXPENSE"?"Comprovante de saída":"Comprovante de contribuição"}</p></header>{["SUPERSEDED","CANCELLED"].includes(receipt.status)&&<strong style={{textAlign:"center",border:"2px solid black",padding:8}}>{receipt.status==="CANCELLED"?"CANCELADO":"SUBSTITUÍDO"}</strong>}<div>Data: {receipt.date.split("-").reverse().join("/")}<br/>Pessoa: {receipt.personName||"Contribuição coletiva"}<br/>Pagamento: {receipt.paymentMethodName}</div><div style={{borderTop:"1px dashed black",borderBottom:"1px dashed black",padding:"10px 0"}}>{receipt.items.map(item=><div key={item.transactionId} data-testid="receipt-item" style={{marginBottom:9}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{item.categoryName}</strong><span style={{whiteSpace:"nowrap"}}>{formatMoney(item.amountCents)}</span></div><small>{item.departmentName}{item.classificationName?` · ${item.classificationName}`:""}</small></div>)}</div><div style={{display:"flex",justifyContent:"space-between",fontWeight:600,fontSize:16}}>Total <span>{formatMoney(receipt.totalCents)}</span></div><footer style={{textAlign:"center",fontSize:9}}><p className="receipt-number">{receipt.number}<br/>Versão {receipt.revision}</p><p>Obrigado por sua contribuição.</p></footer></article></div>;
}
