"use client";
import Link from "next/link";
import {useState} from "react";
import {FileDown,ReceiptText} from "lucide-react";
import {Modal} from "@/components/ui/modal";
import {Button} from "@/components/ui/button";
import type {FinanceTransactionDetail} from "../types/finance-query.types";
import {formatMoney} from "../utils/finance-money";
import {financeLocation} from "../utils/finance-navigation";
import {getFinanceDocumentUrlAction} from "../actions/finance-document.actions";
export function FinanceTransactionDetails({transaction:t,unit,month,onClose,actions}:{transaction:FinanceTransactionDetail;unit:string;month:string;onClose:()=>void;actions?:React.ReactNode}){
 const [error,setError]=useState("");
 return <Modal title="Detalhes do lançamento" className="finance-drawer" onClose={onClose} footer={actions}><div className="stack">{error&&<div role="alert">{error}</div>}<div className="row"><span className="badge">{t.direction==="INCOME"?"Entrada":"Saída"}</span><span className="badge">{t.status==="CANCELLED"?"Cancelado":"Confirmado"}</span><span className="muted">Revisão {t.revision}</span></div><strong style={{fontSize:32,color:t.direction==="INCOME"?"#087F5B":"#B5474D"}}>{formatMoney(t.amountCents)}</strong><h3>{t.categoryName}</h3><div className="grid"><div><p className="muted">Pessoa / favorecido</p>{t.personName||t.beneficiaryName||"Contribuição coletiva"}</div><div><p className="muted">Data · referência</p>{t.date.split("-").reverse().join("/")} · {t.date.slice(0,7).split("-").reverse().join("/")}</div><div><p className="muted">Departamento</p>{t.departmentName}</div>{t.classificationName&&<div><p className="muted">Classificação no lançamento</p>{t.classificationName}</div>}</div>{t.description&&<p>{t.description}</p>}{t.documentNumber&&<p className="muted">Documento: {t.documentNumber}</p>}{t.paymentReference&&<p className="muted">Referência do pagamento: {t.paymentReference}</p>}{t.notes&&<div className="notice">{t.notes}</div>}{t.attendanceId&&<p className="notice">Este item faz parte de um atendimento. O comprovante reúne todas as contribuições da pessoa.</p>}
 <section className="stack"><h3>Comprovantes</h3>{t.receipts.length===0?<p className="muted">Sem comprovante emitido.</p>:t.receipts.map(r=><Link key={r.id} className="row" target="_blank" rel="noopener" href={financeLocation(`/financeiro/comprovantes/${r.id}`,unit,month)}><ReceiptText size={17}/>{r.number} · v{r.revision} · {r.status==="SUPERSEDED"?"Substituído":r.status==="CANCELLED"?"Cancelado":"Vigente"}</Link>)}</section>
 {t.documents.length>0&&<section className="stack"><h3>Anexos</h3>{t.documents.map(d=><Button key={d.id} variant="outline" onClick={async()=>{const popup=window.open("about:blank","_blank");if(popup)popup.opener=null;try{const result=await getFinanceDocumentUrlAction(unit,d.id);if(!result.ok){popup?.close();setError(result.message);return;}if(popup)popup.location.href=result.data.url;else{const a=document.createElement("a");a.href=result.data.url;a.download=d.name;a.click();}}catch{popup?.close();setError("Não foi possível abrir o anexo.");}}}><FileDown size={15}/>{d.name}</Button>)}</section>}
 <section className="stack"><h3>Histórico de alterações</h3>{t.history.map(h=><div className="card" key={h.revision}><strong>Revisão {h.revision}</strong><p>{h.reason}</p>{h.beforeAmountCents!==null&&h.afterAmountCents!==null&&<p className="muted">{formatMoney(h.beforeAmountCents)} → {formatMoney(h.afterAmountCents)}</p>}<span className="muted">{new Date(h.createdAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</span></div>)}</section></div></Modal>;
}
