"use client";

import styled from "styled-components";

export const Layout = styled.div`display:grid;gap:22px;`;
export const Stats = styled.div`display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;@media(max-width:760px){grid-template-columns:1fr;}`;
export const Stat = styled.article`display:flex;align-items:center;gap:13px;border:1px solid ${({theme})=>theme.colors.border.soft};border-radius:16px;background:#fff;padding:17px;box-shadow:${({theme})=>theme.shadows.card};>span{display:grid;width:42px;height:42px;place-items:center;border-radius:13px;background:#eef2ff;color:${({theme})=>theme.colors.brand.primary};}>div strong{display:block;color:${({theme})=>theme.colors.text.title};font-size:20px;font-weight:900;}>div small{display:block;margin-top:2px;color:${({theme})=>theme.colors.text.muted};font-size:11px;font-weight:700;}`;
export const Grid = styled.div`display:grid;grid-template-columns:minmax(0,1fr) minmax(310px,.38fr);gap:20px;align-items:start;@media(max-width:1080px){grid-template-columns:1fr;}`;
export const Card = styled.section`overflow:hidden;border:1px solid ${({theme})=>theme.colors.border.soft};border-radius:19px;background:#fff;box-shadow:${({theme})=>theme.shadows.card};`;
export const CardHeader = styled.div`display:flex;align-items:flex-start;justify-content:space-between;gap:14px;border-bottom:1px solid #edf0f4;padding:20px 22px;h2{margin:0;color:#101828;font-size:16px;font-weight:900;}p{margin:5px 0 0;color:#667085;font-size:12px;font-weight:600;line-height:1.5;}`;
export const CardBody = styled.div`padding:20px 22px;`;
export const Toolbar = styled.div`display:grid;grid-template-columns:minmax(180px,1fr) 150px 150px;gap:10px;margin-bottom:15px;@media(max-width:680px){grid-template-columns:1fr;}`;
export const Control = styled.input`width:100%;min-height:44px;border:1px solid #d9deea;border-radius:10px;outline:0;background:#f8f9fc;padding:0 13px;color:#344054;font-size:12px;font-weight:650;&:focus{border-color:${({theme})=>theme.colors.brand.primary};background:#fff;box-shadow:${({theme})=>theme.shadows.focus};}`;
export const Select = styled.select`width:100%;min-height:44px;border:1px solid #d9deea;border-radius:10px;outline:0;background:#f8f9fc;padding:0 12px;color:#344054;font-size:12px;font-weight:700;&:focus{border-color:${({theme})=>theme.colors.brand.primary};}`;
export const AccessList = styled.div`display:grid;gap:10px;`;
export const AccessCard = styled.article`border:1px solid #e7eaf1;border-radius:14px;background:#fff;`;
export const AccessSummary = styled.div`display:grid;grid-template-columns:minmax(180px,1.2fr) minmax(125px,.6fr) minmax(125px,.6fr) auto;align-items:center;gap:12px;padding:14px;@media(max-width:720px){grid-template-columns:1fr auto;}`;
export const Person = styled.div`display:flex;min-width:0;align-items:center;gap:11px;`;
export const Avatar = styled.span`display:grid;width:40px;height:40px;flex:0 0 auto;place-items:center;border-radius:13px;background:linear-gradient(145deg,#6c82da,#415ba5);color:#fff;font-size:11px;font-weight:900;`;
export const PersonMeta = styled.div`min-width:0;strong{display:block;overflow:hidden;color:#101828;font-size:12px;font-weight:850;text-overflow:ellipsis;white-space:nowrap;}small{display:block;overflow:hidden;margin-top:3px;color:#98a2b3;font-size:10px;font-weight:650;text-overflow:ellipsis;white-space:nowrap;}`;
export const Meta = styled.div`span{display:block;color:#98a2b3;font-size:9px;font-weight:750;text-transform:uppercase;}strong{display:block;margin-top:4px;color:#475467;font-size:11px;font-weight:800;}`;
export const Badge = styled.span<{ $status?: string }>`display:inline-flex;width:fit-content;min-height:25px;align-items:center;border-radius:999px;background:${({$status})=>$status==="ACTIVE"?"#e9f8f0":$status==="BLOCKED"?"#fff0ef":"#f2f4f7"};color:${({$status})=>$status==="ACTIVE"?"#267c5b":$status==="BLOCKED"?"#b5423c":"#667085"};padding:0 9px;font-size:9px;font-weight:850;`;
export const ExpandButton = styled.button`display:grid;width:36px;height:36px;place-items:center;border:1px solid #e3e7ee;border-radius:10px;background:#fff;color:#667085;&:hover{color:${({theme})=>theme.colors.brand.primary};background:#f6f8fc;}`;
export const Editor = styled.div`border-top:1px solid #edf0f4;background:#fafbfc;padding:17px;`;
export const FormGrid = styled.div`display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;@media(max-width:720px){grid-template-columns:1fr;}`;
export const Field = styled.label`display:grid;gap:6px;span{color:#667085;font-size:10px;font-weight:800;}`;
export const Textarea = styled.textarea`width:100%;min-height:76px;border:1px solid #d9deea;border-radius:10px;outline:0;background:#fff;padding:11px 12px;color:#344054;font-size:12px;font-weight:600;resize:vertical;&:focus{border-color:${({theme})=>theme.colors.brand.primary};}`;
export const FormFooter = styled.div`display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:10px;margin-top:13px;`;
export const Button = styled.button<{ $secondary?: boolean; $danger?: boolean }>`display:inline-flex;min-height:42px;align-items:center;justify-content:center;gap:8px;border:1px solid ${({$secondary})=>$secondary?"#d9deea":"transparent"};border-radius:9px;background:${({$secondary,$danger,theme})=>$danger?theme.colors.state.danger:$secondary?"#fff":theme.colors.brand.primary};color:${({$secondary})=>$secondary?"#475467":"#fff"};padding:0 15px;font-size:11px;font-weight:850;&:disabled{opacity:.6;cursor:wait;}`;
export const Alert = styled.div<{ $success?: boolean }>`margin-bottom:12px;border:1px solid ${({$success})=>$success?"#bfe8d4":"#ffd0ce"};border-radius:9px;background:${({$success})=>$success?"#edf9f3":"#fff4f3"};color:${({$success})=>$success?"#267c5b":"#a9413c"};padding:10px 12px;font-size:11px;font-weight:700;line-height:1.5;`;
export const PermissionBox = styled.div`margin-top:15px;border-top:1px dashed #d9deea;padding-top:15px;h3{margin:0;color:#344054;font-size:12px;font-weight:850;}p{margin:5px 0 12px;color:#98a2b3;font-size:10px;font-weight:600;}`;
export const OverrideChips = styled.div`display:flex;flex-wrap:wrap;gap:6px;margin-bottom:12px;span{display:inline-flex;border-radius:999px;background:#eef2ff;color:#415ba5;padding:6px 9px;font-size:9px;font-weight:800;}span[data-effect="DENY"]{background:#fff0ef;color:#b5423c;}`;
export const InviteForm = styled.form`display:grid;gap:13px;`;
export const InviteField = styled.label`display:grid;gap:6px;>span{color:#475467;font-size:10px;font-weight:800;}`;
export const CopyRow = styled.div`display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px;input{min-width:0;height:40px;border:1px solid #cfe0d7;border-radius:9px;background:#f7fcf9;padding:0 10px;color:#267c5b;font-size:10px;font-weight:700;}`;
export const PendingList = styled.div`display:grid;gap:9px;`;
export const Pending = styled.div`border:1px solid #e7eaf1;border-radius:12px;background:#fafbfc;padding:13px;strong{display:block;color:#344054;font-size:11px;font-weight:850;}small{display:block;margin-top:3px;color:#98a2b3;font-size:9px;font-weight:650;}.actions{display:flex;gap:7px;margin-top:10px;button{min-height:32px;border:1px solid #d9deea;border-radius:8px;background:#fff;color:#667085;padding:0 10px;font-size:9px;font-weight:800;}}`;
export const Empty = styled.div`padding:30px 15px;text-align:center;color:#98a2b3;font-size:12px;font-weight:650;`;
export const Spinner = styled.span`width:14px;height:14px;border:2px solid rgba(255,255,255,.4);border-top-color:#fff;border-radius:50%;animation:spin .7s linear infinite;@keyframes spin{to{transform:rotate(360deg)}}`;
